version: "3"
services:
  jupython:
    build: .
    image: jupython/deep_learning
    command: "/opt/conda/bin/jupyter notebook --notebook-dir=/var/app --ip='0.0.0.0' --port=8888 --no-browser --allow-root"
    network_mode: bridge
    container_name: jupyter_deep_learning
    volumes:
      - ./src:/var/app/src
      - ./data:/var/app/data
    ports:
      - 8888:8888
